calendarPage/urls.py
from django.conf.urls import url

from . import views

app_name='calendarPage'

urlpatterns = [
    url(r"^$", views.PostList.as_view(), name="all"),
   
]

reservation_appart/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include,url
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r"^$", views.HomePage.as_view(), name="home"),
    url(r"^calendar/", include("calendarPage.urls", namespace="calendar")),
]

calendarPage/models.py
from django.db import models

class Events(models.Model):
    even_id = models.AutoField(primary_key=True)
    event_name = models.CharField(max_length=255,null=True,blank=True)
    start_date = models.DateTimeField(null=True,blank=True)
    end_date = models.DateTimeField(null=True,blank=True)
    event_type = models.CharField(max_length=10,null=True,blank=True)

    def __str__(self):
        return self.event_name

calendarPage/views.py
# from django.contrib import messages
# from django.contrib.auth.mixins import LoginRequiredMixin

# from django.core.urlresolvers import reverse_lazy
from django.http import Http404
from django.views import generic

# from braces.views import SelectRelatedMixin

# from . import forms
from . import models

from django.contrib.auth import get_user_model
User = get_user_model()


class PostList(generic.ListView):
    model = models.Events
    template_name = "calendarPage/calendarPage_base.html"
    # select_related = ("user", "group")


def event(request):
    all_events = Events.objects.all()
    get_event_types = Events.objects.only('event_type')

    # if filters applied then get parameter and filter based on condition else return object
    if request.GET:  
        event_arr = []
        if request.GET.get('event_type') == "all":
            all_events = Events.objects.all()
        else:   
            all_events = Events.objects.filter(event_type__icontains=request.GET.get('event_type'))

        for i in all_events:
            event_sub_arr = {}
            event_sub_arr['title'] = i.event_name
            start_date = datetime.datetime.strptime(str(i.start_date.date()), "%Y-%m-%d").strftime("%Y-%m-%d")
            end_date = datetime.datetime.strptime(str(i.end_date.date()), "%Y-%m-%d").strftime("%Y-%m-%d")
            event_sub_arr['start'] = start_date
            event_sub_arr['end'] = end_date
            event_arr.append(event_sub_arr)
        return HttpResponse(json.dumps(event_arr))

    context = {
        "events":all_events,
        "get_event_types":get_event_types,

    }
    return render(request,'admin/poll/event_management.html',context)

reservation_appart/views.py
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.views.generic import TemplateView

class TestPage(TemplateView):
    template_name = 'test.html'

class ThanksPage(TemplateView):
    template_name = 'thanks.html'

class HomePage(TemplateView):
    template_name = "index.html"

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return HttpResponseRedirect(reverse("test"))
        return super().get(request, *args, **kwargs)

calendarPage/templates/calendarPage/calendarPage_base.html
{% extends "base.html" %}
{% comment %} https://github.com/fullcalendar/fullcalendar/releases/tag/v4.2.0 {% endcomment %}

{% block content %}

{% load staticfiles %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/4.2.0/core/main.js"></script>
<link href="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/4.2.0/core/main.css" rel='stylesheet' />



<link href="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/4.2.0/daygrid/main.js" rel='stylesheet' />
<script src="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/4.2.0/daygrid/main.js"></script>

<link href="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/4.2.0/timegrid/main.css" rel='stylesheet' />
<script src="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/4.2.0/timegrid/main.js"></script>


<link href="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/4.2.0/list/main.css" rel='stylesheet' />
<script src="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/4.2.0/list/main.js"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/4.2.0/interaction/main.js"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/4.2.0/bootstrap/main.js"></script>
<link href="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/4.2.0/bootstrap/main.css" rel='stylesheet' />




<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.18.1/moment.min.js"></script>

<script>

  document.addEventListener('DOMContentLoaded', function() {
    var calendarEl = document.getElementById('calendar');

    var calendar = new FullCalendar.Calendar(calendarEl, {
      plugins: [ 'dayGrid','timeGrid', 'list','interaction','bootstrap' ],
      defaultView: 'dayGridMonth',
      themeSystem:'bootstrap',
      editable:true,
      selectable:true,
      selectHelper:true,
    header: {
            left: 'prev,next today',
            center: 'title',
            right: 'month,agendaWeek,agendaDay'
        },

      
    });

    

    calendar.render();
  });


</script>

<script>

    $(document).ready(function() {

        $('#calendar').fullCalendar({
            defaultDate: '2016-07-19',
            editable: true,
            eventLimit: true, // allow "more" link when too many events
            events: [
                {% for i in events %}
                {
                    title: "{{ i.event_name}}",
                    start: '{{ i.start_date|date:"Y-m-d" }}',
                    end: '{{ i.end_date|date:"Y-m-d" }}',

                },
                {% endfor %}

            ]
        });

    });

</script>

    <h1>Welcome to reservation appartement</h1>
    <div id='calendar'></div>

{% endblock %}

calendarPage/templates/calendarPage/calendarPage_detail.html
{% extends "groups/group_base.html" %}

{% block pregroup %}


<h1>{{group.name}}</h1>
<h2> Member Count: {{group.members.count}}</h2>

  <div class="content">


				{% if user in group.members.all %}
					<a href="{% url 'groups:leave' slug=group.slug %}" class="btn btn-lg btn-fill btn-warning"><span class="glyphicon glyphicon-remove-circle"></span> Leave</a>
				{% else %}
					<a href="{% url 'groups:join' slug=group.slug %}" class="btn btn-lg btn-fill btn-warning"><span class="glyphicon glyphicon-ok-circle"></span> Join</a>
				{% endif %}



</div>

{% endblock %}


{% block group_content %}

<div class="col-md-8">
	{% if group.posts.count == 0 %}
	<h2>No posts in this group yet!</h2>

	{% else %}

		{% for post in group.posts.all %}
			{% include "posts/_post.html" %}
		{% endfor %}

	{% endif %}
</div>
{% endblock %}

calendarPage/templates/calendarPage/calendarPage_form.html
{% extends "groups/group_base.html" %}
{% load bootstrap3 %}

{% block group_content %}
<h4>Create A New Group</h4>
  <form method="POST" action="{% url 'groups:create' %}" id="groupForm">
  	{% csrf_token %}
  	{% bootstrap_form form %}
  	<input type="submit" value="Create" class="btn btn-primary btn-large">
  </form>
{% endblock %}

calendarPage/templates/calendarPage/calendarPage_list.html
{% extends "groups/group_base.html" %}

{% block pregroup %}
<div class="col-md-4">
	<div class="content">
		{% if user.is_authenticated %}
		<h2>
			Welcome back
			<a href="{% url 'posts:for_user' username=user.username %}">@{{user.username }}</a>
		</h2>

    {% endif %}
			<h2>Groups</h2>

			<p>Welcome to the Groups Page! Select a Group with a shared interest!</p>
	</div>
	{% if user.is_authenticated %}
	<a href="{% url 'groups:create' %}" class="btn btn-md btn-fill btn-warning"><span class="glyphicon glyphicon-plus-sign"></span> Create New Group!</a>
	{% endif %}
</div>
{% endblock %}

{% block group_content %}
<div class="col-md-8">
	<div class="list-group">
		{% for group in object_list %}
		  <a class="list-group-item" href="{% url 'groups:single' slug=group.slug %}">
			     <h3 class="title list-group-item-heading">{{ group.name }}</h3>
			<div class="list-group-item-text container-fluid">
				{{ group.description_html|safe }}
				<div class="row">
					<div class="col-md-4">
						<span class="badge">{{ group.members.count }}</span> member{{ group.members.count|pluralize }}
					</div>
					<div class="col-md-4">
						<span class="badge">{{ group.posts.count }}</span> post{{ group.posts.count|pluralize }}
					</div>
				</div>
			</div>
		</a>
		{% endfor %}
	</div>
</div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
  <head>
    <meta charset="utf-8">
    <title>Reservation appartement</title>
    <!-- Latest compiled and minified CSS -->

    <link href='https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css' rel='stylesheet' />

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.js" ></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment.js" ></script>
    {% comment %} <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script> {% endcomment %}


    <link href='https://use.fontawesome.com/releases/v5.0.6/css/all.css' rel='stylesheet'>

    {% comment %} <link rel="stylesheet" href="{% static 'simplesocial/css/master.css'%}"> {% endcomment %}


  </head>


  <body>

    <nav class="navbar  mynav" role="navigation" id="navbar">
    			<div class="container">

            <a class="navbar-brand mynav" href="{% url 'home' %}">Reservation appartement</a>

    					<ul class="nav navbar-nav navbar-right">
    						{% if user.is_authenticated %}
                      <li><a href="#" class="btn btn-simple">Post</a></li>
                      <li><a href="#" class="btn btn-simple">Calendrier</a></li>
                      <li><a href="#" class="btn btn-simple">Reserver</a></li>
                      <li><a href="#" class="btn btn-simple">Log out</a></li>
    						{% else %}
    						      <li><a href="{% url 'calendarPage:all' %}" class="btn btn-simple">Calendrier</a></li>
    						      <li><a href="#" class="btn btn-simple">Log in</a></li>
    						      <li><a href="#" class="btn btn-simple">Sign up</a></li>
    						{% endif %}
    					</ul>



    			</div>
    		</nav>
        <div class="container mycontent">
          {% block content %}

          {% endblock %}

        </div>



<canvas id="canvas"></canvas>



  </body>
  {% comment %} <script src="{% static "simplesocial/js/master.js"%}" type="text/javascript" ></script> {% endcomment %}
</html>

templates/index.html
{% extends "base.html" %}
{% comment %} https://github.com/fullcalendar/fullcalendar/releases/tag/v4.2.0 {% endcomment %}

{% block content %}

{% comment %} {% load staticfiles %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/4.2.0/core/main.js"></script>
<link href="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/4.2.0/core/main.css" rel='stylesheet' />



<link href="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/4.2.0/daygrid/main.js" rel='stylesheet' />
<script src="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/4.2.0/daygrid/main.js"></script>

<link href="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/4.2.0/timegrid/main.css" rel='stylesheet' />
<script src="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/4.2.0/timegrid/main.js"></script>


<link href="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/4.2.0/list/main.css" rel='stylesheet' />
<script src="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/4.2.0/list/main.js"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/4.2.0/interaction/main.js"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/4.2.0/bootstrap/main.js"></script>
<link href="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/4.2.0/bootstrap/main.css" rel='stylesheet' />




<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.18.1/moment.min.js"></script>

<script>

  document.addEventListener('DOMContentLoaded', function() {
    var calendarEl = document.getElementById('calendar');

    var calendar = new FullCalendar.Calendar(calendarEl, {
      plugins: [ 'dayGrid','timeGrid', 'list','interaction','bootstrap' ],
      defaultView: 'dayGridMonth',
      themeSystem:'bootstrap',
      editable:true,
      selectable:true,
      selectHelper:true,
    eventSources: [
            {
                color: '#306EFE',   
                textColor: '#ffffff',
                events: [
                    {
                        title: 'My Big Event',
                        start: '2019-08-09',
                        end: '2019-08-10'
                    },
                    {
                        title: 'My Second Big Event',
                        start: '2019-08-11',
                        end: '2019-08-13'
                    }  
                 ]
            }
    ],
    
    header: {
            left: 'prev,next today',
            center: 'title',
            right: 'month,agendaWeek,agendaDay'
        },
   footer: {
            left: 'prev,next today myCustomButton',
            center: 'title',
            right: 'month,agendaWeek,agendaDay'
        },


      
    });

    

    calendar.render();
  });

calendar.on('dateClick', function(info) {
  console.log('clicked on ' + info.dateStr);
});
</script> {% endcomment %}


    <h1>Welcome to reservation appartement</h1>
    {% comment %} <div id='calendar'></div> {% endcomment %}

{% endblock %}

templates/test.html
{% extends "base.html" %}
{% block content %}
<div class="container">
  <h1>You are now logged in!</h1>
  <h2><a href="{% url 'groups:all'%}">Go to Groups</a></h2>


</div>




{% endblock %}

templates/thanks.html
{% extends "base.html" %}
{% block content %}
<h1>Thanks for visiting! Come back soon!</h1>

{% endblock %}